ConcealNetwork/conceal-core

README.md

version update

---

src/CryptoNoteConfig.h
src/CryptoNoteCore/Blockchain.cpp
src/SimpleWallet/SimpleWallet.cpp

Hardfork details still need to be decided

enforce minimim mixin of 2

---

src/SimpleWallet/SimpleWallet.cpp

Fixes several warnings and generally better coding practice

miscellaneous fixes

---

README.md
src/Platform/Windows/System/Dispatcher.cpp
src/Platform/Windows/System/Ipv4Resolver.cpp
src/Platform/Windows/System/TcpConnection.cpp
src/Platform/Windows/System/TcpConnector.cpp
src/Platform/Windows/System/TcpListener.cpp

We will need to update the hosted URL for boost libs once we find a home for it.

Updates to support MSVC 14.2 (2019) and Boost 1.70.0

---

src/SimpleWallet/SimpleWallet.cpp

Adding support for Conceal ID aliases to ConcealWallet.

Conceal ID changes

---

.gitignore
src/PaymentGate/PaymentServiceJsonRpcMessages.cpp
src/PaymentGate/PaymentServiceJsonRpcMessages.h
src/PaymentGate/PaymentServiceJsonRpcServer.cpp
src/PaymentGate/PaymentServiceJsonRpcServer.h
src/PaymentGate/WalletService.cpp
src/PaymentGate/WalletService.h
src/Wallet/WalletErrors.h

Add a call in walletd to split integrated addresses and return the address and payment id

Walletd split integrated

---

src/CryptoNoteCore/Currency.cpp
src/SimpleWallet/PasswordContainer.cpp
src/SimpleWallet/PasswordContainer.h
src/SimpleWallet/SimpleWallet.cpp
src/SimpleWallet/SimpleWallet.h

* Fixed the `--testnet` flag so that it upgrades with every current *hardfork*. If you [read here](https://github.com/LithyRiolu/Resources/tree/master/Snippets#cryptonote-testnet-fix), it should explain better.
***
* Added total balance to `balance` arg
* Added confirm password when creating & loading a wallet
* Added `outgoing_transfers` arg

Minor changes

---

src/CryptoNoteCore/Blockchain.cpp
src/CryptoNoteCore/Blockchain.h
src/CryptoNoteCore/Core.cpp
src/CryptoNoteCore/Core.h
src/Daemon/Daemon.cpp
src/PaymentGate/WalletService.cpp
src/PaymentGateService/PaymentGateService.cpp
src/Wallet/WalletGreen.cpp

- Add block-chain explorer mode
- Indices only built when explorer mode is enabled
- Fix incorrect confirmations from getTransactions in walletd
- Fix issue with fusion transactions in walletd.

version 6.1.8

---

src/Rpc/CoreRpcServerCommandsDefinitions.h
src/Rpc/RpcServer.cpp
src/Rpc/RpcServer.h

* Adds `/gettransactionsbypaymentid` RPC method

Get Transactions by Payment ID - RPC method

---

src/Common/Util.cpp
src/WalletLegacy/WalletTransactionSender.cpp

Follow the method that TRTL uses to select outputs when sending, which is to make base10 buckets, separate the outputs into the buckets, and then pick an output, one bucket at a time.

New tx output selection

---

src/Rpc/CoreRpcServerCommandsDefinitions.h
src/Rpc/RpcServer.cpp
src/Rpc/RpcServer.h
src/SimpleWallet/SimpleWallet.cpp

Added an RPC call 'getaltblockslist' to list out alternate blocks in the blockchain.

Alternate blocks rpc call

---

src/Rpc/RpcServer.cpp

Fixes incorrect alternate chain / orphan block status in some RPC calls and adds another call to show blocks from the alternate chain in current memory.

Fix orphan block status on the RPC server

---

src/Transfers/BlockchainSynchronizer.cpp

Fix clang build

---

.vscode/settings.json
src/CryptoNoteCore/Core.cpp
src/CryptoNoteCore/Core.h
src/CryptoNoteCore/ICore.h
src/NodeRpcProxy/NodeRpcProxy.cpp
src/NodeRpcProxy/NodeRpcProxy.h
src/Rpc/CoreRpcServerCommandsDefinitions.h
src/Rpc/RpcServer.cpp
src/Rpc/RpcServer.h

Added
getblockhash
getblocktimestamp
getblockbyheight
gettransactionsbypaymentid

Daemon rpc calls

---

README.md

Updated bash instructions

---

README.md

Reverts ConcealNetwork/conceal-core#242

Revert "fetch update"

---

src/ConnectivityTool/ConnectivityTool.cpp
src/PaymentGate/PaymentServiceJsonRpcMessages.h

Mixins changed to 5. Ringsize = Mixins + 1 = 6

Fix Payment Service Ringsize

---

CMakeLists.txt
src/Serialization/BinaryInputStreamSerializer.cpp
src/Serialization/KVBinaryInputStreamSerializer.cpp

reduce string limits to a sane value

reduce string value limit

---

CMakeLists.txt
arm.cmake

Split arm in CMakeLists to be able to use it for desktop

Split arm part

---

CMakeLists.txt
src/CryptoNoteCore/Currency.cpp

Version 6.6.4

---

src/SimpleWallet/SimpleWallet.cpp
tools/deploy.sh
tools/make_swap.sh

Mimic behaviour seen in shells, such as Bash/ZSH/CSH etc, by expanding the tilde character (`~`) to the user's home directory via an environmental variable. In Windows - `%USERPROFILE%`, in Linux/BSD/Darwin - `$HOME`
Shell script to create swap file with the required size to equal a combined total of 13GB, the amount that was recommended in the README
Shell script that automates obtaining, building and installation w/ basic interaction with `concealwallet` - useful for deploying on multiple systems at a time

Quality of Life Improvements

---

src/BlockchainExplorer/BlockchainExplorerDataBuilder.cpp
src/ConcealWallet/ConcealWallet.cpp
src/CryptoNoteConfig.h
src/CryptoNoteCore/Blockchain.cpp
src/CryptoNoteCore/Blockchain.h
src/CryptoNoteCore/Core.cpp
src/CryptoNoteCore/Currency.cpp
src/CryptoNoteCore/Currency.h
src/CryptoNoteCore/ITransactionValidator.h
src/CryptoNoteCore/SwappedVector.h
src/CryptoNoteCore/TransactionPool.cpp
src/PaymentGate/WalletService.cpp
src/Rpc/RpcServer.cpp
tests/UnitTests/TestCurrency.cpp
tests/UnitTests/TransactionPool.cpp

- check correct deposit term and interest
- use same fee calculation everywhere

Update currency and fee calculation

---

src/CryptoNoteCore/Blockchain.cpp

Move the cache file out of the way when writing

Implement cache file backup
