ConcealNetwork/conceal-core

src/SimpleWallet/SimpleWallet.cpp

Previously, a user would only see the new wallet address and view key when generating a new wallet. The user would need to enter the export_keys to then see the secret key.

Display secret key when generating a new wallet

---

src/SimpleWallet/SimpleWallet.cpp

Otherwise it will use an invalid paymentID to create an invalid integrated address if given

validate paymentID supplied to create_integrated

---

include/IWalletLegacy.h
src/SimpleWallet/SimpleWallet.cpp
src/WalletLegacy/WalletLegacy.cpp
src/WalletLegacy/WalletLegacy.h

Instead of just showing the number of available outputs, actually show the public key and associated amount for each output, along with the count

wallet: show info about each out on outputs command

---

include/IWallet.h
src/PaymentGate/PaymentServiceJsonRpcMessages.cpp
src/PaymentGate/PaymentServiceJsonRpcMessages.h
src/PaymentGate/PaymentServiceJsonRpcServer.cpp
src/PaymentGate/PaymentServiceJsonRpcServer.h
src/PaymentGate/WalletService.cpp
src/PaymentGate/WalletService.h
src/PaymentGate/WalletServiceErrorCategory.h
src/Wallet/WalletGreen.cpp
src/Wallet/WalletGreen.h

One of the issues with the service wallet is that if you need to restore additional wallets with keys, there is mechanism to import the privateSpendKeys of more than one wallet at a time. With createAddressList you can provide an array of privateSpendKeys in the params and all corresponding wallets will be created in the container.

Add createAddressList to walletd

---

src/CryptoNoteCore/Blockchain.cpp

This change ensures that the signature count for the coinbase transaction does not exceed 1 to prevent a blockchain bloat exploit, where the coinbase transaction could be added with additional signatures. Over time this could result in a significant increase in the size of the blockchain. Analysis of the chain so far does not show any use of the exploit.

Check coinbase transaction signature count

---

CMakeLists.txt
external/CMakeLists.txt

When compiling, gtest will spam text like this;
```bash
/home/lithy/lithe-dev/external/gtest/include/gtest/internal/gtest-port.h:310:5: warning: "_MSC_VER" is not defined, evaluates to 0 [-Wundef]
#if _MSC_VER >= 1500
^~~~~~~~
/home/lithy/lithe-dev/external/gtest/include/gtest/internal/gtest-port.h:398:5: warning: "GTEST_OS_WINDOWS" is not defined, evaluates to 0 [-Wundef]
#if GTEST_OS_WINDOWS
^~~~~~~~~~~~~~~~
In file included from /home/lithy/lithe-dev/external/gtest/include/gtest/internal/gtest-internal.h:39:0,
from /home/lithy/lithe-dev/external/gtest/include/gtest/gtest.h:58,
from /home/lithy/lithe-dev/external/gtest/src/gtest-all.cc:39:
/home/lithy/lithe-dev/external/gtest/include/gtest/internal/gtest-port.h:422:5: warning: "GTEST_OS_LINUX_ANDROID" is not defined, evaluates to 0 …
```

Silent gtest

---

src/CryptoNoteCore/CryptoNoteSerialization.cpp
src/CryptoNoteCore/CryptoNoteSerialization.h
src/CryptoNoteCore/TransactionExtra.cpp
src/Wallet/LegacyKeysImporter.cpp
src/Wallet/WalletSerialization.cpp
src/Wallet/WalletSerialization.h
src/WalletLegacy/WalletLegacySerializer.cpp
src/WalletLegacy/WalletLegacySerializer.h
src/crypto/chacha8.c
src/crypto/chacha8.h
tests/UnitTests/Chacha8.cpp

I noticed there are 2 instances of `chacha8` within Conceal. If you take a look within `conceal-core/src/crypto`, you can see we have `chacha.c/h` and `chacha8.c/h` with minor differences.
I've fixed it up and and deleted the other files so we dont get confused between the two. You can see what i've done here; https://github.com/LithyRiolu/lithe/commit/f53c9ba814eac3fc09b99bc778342eba1d8c5513 and it passes the AppVeyor CI for windows.
I've tested it also by creating new wallets, loading them and mining with them (to verify incoming txs) and everything looks legit.

Chacha8 cleanup

---

src/SimpleWallet/SimpleWallet.cpp

`logger(INFO...)` has been replaced with a standard `std::cout` declaration to avoid keys being leaked in the log file when you create a new wallet. This is a security risk if you share your machine

SW: Remove logging from creation

---

src/Common/BlockingQueue.cpp
src/Common/Math.cpp
src/CryptoNoteCore/SwappedMap.cpp
src/CryptoNoteCore/SwappedVector.cpp
src/Logging/LoggerMessage.cpp
src/PaymentGate/WalletService.cpp
src/Platform/Linux/System/Dispatcher.cpp
src/Platform/Linux/System/TcpConnection.cpp
src/Platform/Linux/System/TcpConnector.cpp
src/Platform/Linux/System/TcpListener.cpp
src/Platform/OSX/System/Dispatcher.cpp
src/Platform/OSX/System/TcpConnection.cpp
src/Platform/OSX/System/TcpConnector.cpp
src/Platform/OSX/System/TcpListener.cpp
src/Rpc/RpcServer.cpp
src/System/Ipv4Address.cpp
src/Transfers/SynchronizationState.cpp
src/Wallet/WalletGreen.cpp
src/Wallet/WalletSerialization.cpp

*I think thats most of the warnings covered*. Theres just the 2 about that look something like:
```
warning: unused variable ‘tx’ [-Wunused-variable]
auto& tx = m_transactions[id];
```
and: `for (auto& out : outputs) {` but they shouldn't be a problem

Fixes a few compiler warnings

---

.github/workflows/check.yml
src/Daemon/DaemonCommandsHandler.cpp
src/P2p/NetNode.cpp
src/SimpleWallet/SimpleWallet.cpp

Boost 1.60 is no accepted on Homebrew, so we use Boost 1.73 for macOS instead. However, due to some changes and to maintain compatibility with the version of Boost used on Ubuntu 16.04, a few changes had to be made on the use of placeholders.

Fix macos build actions

---

.github/workflows/macOS.yml

Fixing error with boost version in GitHub Actions

Fixing macOS build

---

include/BinaryArray.hpp
include/CryptoNote.h
include/CryptoTypes.h
include/INode.h
include/ITransaction.h
src/Common/BinaryArray.hpp
src/CryptoNoteCore/CryptoNoteFormatUtils.cpp
src/CryptoNoteCore/CryptoNoteFormatUtils.h
src/CryptoNoteCore/CryptoNoteSerialization.cpp
src/CryptoNoteCore/CryptoNoteSerialization.h
src/CryptoNoteCore/Transaction.cpp
src/CryptoNoteCore/TransactionPrefixImpl.cpp
src/InProcessNode/InProcessNode.cpp
src/InProcessNode/InProcessNode.h
src/NodeRpcProxy/NodeRpcProxy.cpp
src/NodeRpcProxy/NodeRpcProxy.h
src/PaymentGate/NodeFactory.cpp
src/Rpc/RpcServer.cpp
src/Transfers/TransfersConsumer.cpp
src/Wallet/WalletGreen.cpp
src/Wallet/WalletGreen.h
src/WalletLegacy/WalletLegacy.cpp
src/crypto/crypto-util.h
src/crypto/crypto.cpp
src/crypto/crypto.h

Introduces support for deterministic transactions keys, also known as secret keys. Previously, a user needed to note down the secret key as soon as the transaction is sent. Now starting from the latest version of the wallet, we generated the secret key based on the inputs of the transactions, which enables us to get the secret key for the transaction at any point to provide proof of payment or that funds were sent to a specific address.

Deterministic transaction keys

---

src/SimpleWallet/SimpleWallet.cpp
src/SimpleWallet/SimpleWallet.h

Exports private keys to a simple .txt file. Users tend to copy their private keys into a new text file so this saves a job.
```
Conceal Keys Backup
Wallet file name: my_first.wallet
Private spend key: bfb...
Private view key: 0f1...
Mnemonic seed: nylon nobody umbrella ...
```
https://github.com/cartoon-face/Mimosa/pull/5

`save_keys` command in concealwallet

---

src/Logging/LoggerMessage.cpp

`std::streambuf::setp(char, char)` doesn't need or use `pptr()` as it only needs 2 char inputs, currently occupied by `pbase()` and `epptr()`

Remove unused variable from Logging

---

src/BlockchainExplorer/BlockchainExplorer.cpp
src/CryptoNoteCore/Miner.cpp
src/CryptoNoteCore/OnceInInterval.h
src/CryptoNoteCore/TransactionPool.cpp
src/CryptoNoteProtocol/CryptoNoteProtocolHandler.cpp
src/Logging/LoggerMessage.cpp
src/Mnemonics/language_base.h
src/NodeRpcProxy/NodeRpcProxy.cpp
src/P2p/NetNode.cpp
src/Wallet/PoolRpcServer.cpp
src/Wallet/WalletRpcServer.cpp
src/WalletLegacy/WalletTransactionSender.cpp
src/crypto/keccak.c

This should clear up all the code smell minor warnings on SonarCloud

SonarCloud code smell minors

---

src/SimpleWallet/SimpleWallet.cpp
src/SimpleWallet/SimpleWallet.h

Over the years of development to client wallet, there have been many useful commands implemented. When a user types `help`, there could be a lot to make a new user scared because of the shear amount of commands there is. I've split all the commands into two menu's, `help` and `ext_help`.
The command `save_keys` has now been improved to be able to save multiple backups without overwriting the previous.
In example: If I've made multiple wallets in `concealwallet` and decided to back each one up, we would end up with only one set of keys being back as each backup would overwrite the last.
Now this function has been changed so it includes the wallet filename within the filename of the backed up keys. This also covers 1 SonarCloud code smell by making use of `args` in this command
**Command:** …

`concealwallet` Command Improvements

---

src/CryptoNoteCore/Blockchain.cpp
src/CryptoNoteCore/Blockchain.h
src/CryptoNoteCore/Core.cpp
src/CryptoNoteCore/Core.h
src/CryptoNoteCore/ICore.h
src/CryptoNoteCore/TransactionPool.cpp
src/CryptoNoteCore/TransactionPool.h
src/Rpc/CoreRpcServerCommandsDefinitions.h
src/Rpc/RpcServer.cpp
src/Rpc/RpcServer.h

This adds required CORS headers as well as two methods that allow browser wallet to work with node directly: POST `getrawtransactionsbyheights` and `getrawtransactionspool` and corresponding GET handlers `/get_raw_transactions_by_heights`, `/getrawtransactionspool`

RPC: get raw txs and mempool methods

---

src/CryptoNoteCore/Blockchain.cpp
src/CryptoNoteCore/Checkpoints.cpp
src/Daemon/Daemon.cpp

This will allow sync 10x faster until the last checkpoints. The condition not to check POW under the checkpoint zone was not triggered, which is fixed by this PR.

Fix checkpoints loading | Huge sync speed boost

---

src/Rpc/CoreRpcServerCommandsDefinitions.h
src/Rpc/RpcServer.cpp
src/Rpc/RpcServer.h

Generally, for web-wallet, this will allow it to get random outs for sending with mixins in JSON format without the need to implement parsing of binary output.

Separate bin and json /getrandom_outs

---

src/SimpleWallet/SimpleWallet.cpp
src/SimpleWallet/SimpleWallet.h

Previous implementation of this would cause a break. It seems it was put outside the namespace so that it could be used in the transfer command. Here, I've adjusted it so the variable comes over to the transfer command without loosing data.

Remote node address implementation change

---

src/SimpleWallet/SimpleWallet.cpp
src/SimpleWallet/SimpleWallet.h

Save all transactions to file

---

README.md

Both GCC and G++ are included with the `build-essential` package, so including them in the dependency list (ie `apt install .....`) is redundant.
On Ubuntu and Debian Based Systems, `python` refers to Python 2, and the package that is actually needed is named `python3-dev`. Attempting to install `python-dev` threw this error on Linux Mint 21:
```
Package python-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
python2-dev:i386 python2:i386 python2-dev python2 python-dev-is-python3
E: Package 'python-dev' has no installation candidate
```
Changed the header of 'Building/Ubuntu' to 'Building/Linux', as the commands there are pretty …

README: Updated Dependencies & Other Stuff

---

src/Platform/Linux/System/Dispatcher.cpp

Included "pthread.h" so that it will build on Arch and Arch based distributions, such as Manjaro

Platform/Linux/System/Dispatcher: 'pthread' Header

---

src/ConcealWallet/ClientHelper.cpp
src/ConcealWallet/ClientHelper.h
src/ConcealWallet/ConcealWallet.cpp
src/ConcealWallet/ConcealWallet.h
src/ConcealWallet/main.cpp

* changes to deposit status output. @ TurdBird in Discord said:
> "can someone change the wallet time lock from SPENT, to WITHDRAWN? i see this all the time, and it gives ppl the wrong idea. thanks!"
* `check_address` command to verify $CCX addresses
* move balance function to `client_helper` so then we can call `.balances(...)` in main.cpp to show all balances in wallet, main & deposit.

`concealwallet` Improvements 

---

src/CryptoNoteCore/Core.cpp
src/Daemon/Daemon.cpp
src/NodeRpcProxy/NodeRpcProxy.cpp
src/Rpc/RpcServer.cpp
src/Rpc/RpcServer.h
src/Rpc/RpcServerConfig.cpp
src/Rpc/RpcServerConfig.h

*  implement `isSynchronized` query in NodeRPC
* `try` guard a mined block finding txs in the pool
* if another block is received, we shouldn't take them txs from the pool
* updates cors implementation
* Works on my machine

Development (Needs testing)

---

.github/workflows/check.yml
.github/workflows/macOS.yml
.github/workflows/ubuntu18.yml
.github/workflows/ubuntu20.yml
.github/workflows/ubuntu22.yml
.github/workflows/windows.yml

Fix GitHub Actions warnings
- https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
- https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

GitHub Actions update

---

include/ITransaction.h
include/ITransfersContainer.h
include/IWallet.h
src/CryptoNoteConfig.h
src/CryptoNoteCore/Currency.cpp
src/CryptoNoteCore/Currency.h
src/CryptoNoteCore/Transaction.cpp
src/PaymentGate/NodeFactory.cpp
src/PaymentGate/PaymentServiceJsonRpcMessages.cpp
src/PaymentGate/PaymentServiceJsonRpcMessages.h
src/PaymentGate/PaymentServiceJsonRpcServer.cpp
src/PaymentGate/PaymentServiceJsonRpcServer.h
src/PaymentGate/WalletService.cpp
src/PaymentGate/WalletService.h
src/PaymentGate/WalletServiceErrorCategory.h
src/PaymentGateService/ConfigurationManager.cpp
src/PaymentGateService/ConfigurationManager.h
src/PaymentGateService/PaymentGateService.cpp
src/PaymentGateService/PaymentGateService.h
src/PaymentGateService/PaymentServiceConfiguration.cpp
src/PaymentGateService/PaymentServiceConfiguration.h
src/PaymentGateService/RpcNodeConfiguration.cpp
src/PaymentGateService/RpcNodeConfiguration.h
src/Wallet/WalletGreen.cpp
src/Wallet/WalletGreen.h
tests/UnitTests/TestWalletService.cpp

wallet / WalletGreen improvements
- fix minor problems
- reduce duplication
- use deterministic transaction secret key

Walletd improvements
